#! /bin/bash


#########################################################
#
#########################################################


BS=/home/mezz/Documents/eda132/eda132_3/files/Planning/Blocksworld_32bit/GENERATOR/bwstates.1/bwstates

TR=/home/mezz/Documents/eda132/eda132_3/files/Planning/Blocksworld_32bit/GENERATOR/2pddl/2pddl



$BS -s 2 -n $1 > STATES
$TR -d STATES -n $1 

rm STATES


