#! /bin/bash


#########################################################
#
#########################################################


BS=/h/d8/e/ada10lgu/Documents/eda132/repo/files/Planning/Blocksworld_32bit/GENERATOR/bwstates.1/bwstates

TR=/h/d8/e/ada10lgu/Documents/eda132/repo/files/Planning/Blocksworld_32bit/GENERATOR/2pddl/2pddl



$BS -s 2 -n $1 > STATES
$TR -d STATES -n $1 

rm STATES


